### ISSUE TITLE
Specifying a hostname no longer works after upgrade to 0.18.6

### ISSUE THREAD

**Issue by hogend** [kongo09/philips-airpurifier-coap#122]
HA 2024.1.3:

After upgrading from 0.17.5 to 0.18.6, specifying a hostname no longer works, where, according to the  README, it should.
The following error message is generated:
```
Error setting up entry AC2889 Kitchen for philips_airpurifier_coap

Traceback (most recent call last):
  File "/home/hass/virtualenv3.11/lib/python3.11/site-packages/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/.homeassistant/custom_components/philips_airpurifier_coap/__init__.py", line 111, in async_setup_entry
    mac = await async_get_mac_address_from_host(hass, host)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/.homeassistant/custom_components/philips_airpurifier_coap/__init__.py", line 96, in async_get_mac_address_from_host
    ip_addr = ip_address(host)
              ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'air-purifier-living.rmer.nl' does not appear to be an IPv4 or IPv6 address
```

While name resolution appears to work as expected:
```
$ host air-purifier-living.rmer.nl
air-purifier-living.rmer.nl has address 192.168.7.80
```

The problem is likely the use of the ip_address() function which only accepts ipv4 or ipv6 address specifications.

**Comment by kongo09** [comment]
Can you please try v0.18.7-beta.1 and see if this fixes your problem?

**Comment by hogend** [comment]
This works again. Thanks!

**Comment by kongo09** [comment]
great, thanks for testing!
