### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'values'

### ISSUE THREAD

**Issue by tjorim** [kongo09/philips-airpurifier-coap#127]
```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:145
First occurred: 01:36:45 (13 occurrences)
Last logged: 20:43:49

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiocoap/tokenmanager.py", line 61, in shutdown
    await self.token_interface.shutdown()
  File "/usr/local/lib/python3.12/site-packages/aiocoap/messagemanager.py", line 65, in shutdown
    for messageerror_monitor, cancellable in self._active_exchanges.values():
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by kongo09** [comment]
What makes you think this is an error of this integration?

**Comment by tjorim** [comment]
Because of the `aiocoap`, you don't think it's coming from here?

**Comment by kongo09** [comment]
I don't know. You could disable this integration and see if the error stays or goes away
