### ISSUE TITLE
Request for AC0650/10

### ISSUE THREAD

**Issue by ProAdmin007** [kongo09/philips-airpurifier-coap#149]
Hi I'm trying to get data from my air purifier, but I get the following error:

```
aioairctrl --host <IP-HERE> status --json
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 549, in _loop_reading
    res = fut.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 462, in finish_recv
    return ov.getresult()
OSError: [WinError 1234] No service is operating at the destination network endpoint on the remote system
```

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\x\env\Scripts\aioairctrl.exe\__main__.py", line 7, in <module>
  File "C:\Users\x\env\lib\site-packages\aioairctrl\cli.py", line 139, in main
    asyncio.run(async_main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\x\env\lib\site-packages\aioairctrl\cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
  File "C:\Users\x\env\lib\site-packages\aioairctrl\coap\client.py", line 41, in create
    await obj._init()
  File "C:\Users\x\env\lib\site-packages\aioairctrl\coap\client.py", line 36, in _init
    await self._sync()
  File "C:\Users\x\env\lib\site-packages\aioairctrl\coap\client.py", line 57, in _sync
    response = await self._client_context.request(request).response
  File "C:\Users\x\env\lib\site-packages\aiocoap\protocol.py", line 606, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "C:\Users\x\env\lib\site-packages\aiocoap\protocol.py", line 665, in _run
    blockresponse = await blockrequest.response
aiocoap.error.NetworkError: [WinError 1234] No service is operating at the destination network endpoint on the remote system
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021669A5D1F0>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 751, in call_soon
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```

I can ping the device, but no ports are open.

Hope someone can help me.

**Comment by kongo09** [comment]
What happens if you try to setup the device from inside HA?

**Comment by ProAdmin007** [comment]
![image](https://github.com/user-attachments/assets/6e372f91-c720-4123-8b4c-707232e369f7)
This is what happens:
Can't connect

**Comment by kongo09** [comment]
Seems to be the connectivity problem that plagues many people. And you're right, if you cannot connect from the command line (from the same machine), then HA cannot do it either. I only asked because some people used different machines and then found out that they have a network segmentation like vlan or so that doesn't allow them to connect.

Some people get lucky by power cycling the device and connecting then. Others use the Air+ app during the connecting attempt and that helped. But some never got it to connect.

The alternative could be to try the original code here: https://github.com/rgerganov/py-air-control

Maybe your device doesn't speak encrypted CoAP but one of the other two protocols. Unfortunately, this integration only makes use of encrypted CoAP.
