### ISSUE TITLE
No fan entity created when adding device

### ISSUE THREAD

**Issue by AlexisBild77** [kongo09/philips-airpurifier-coap#192]
Hello!
I have problem while adding ac1715 purifier - no fan entity created, while all sensors are available. 

Trace when rebooting integration bellow - says TURN_OFF attribute is missing.

Will be grateful for advice :)

> ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/philips_airpurifier_coap/config_flow.py", line 196, in async_step_confirm
    return self.async_create_entry(config_entry_name, data=user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConfigFlow.async_create_entry() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
2024-11-15 13:03:24.866 ERROR (MainThread) [homeassistant.components.fan] Error while setting up philips_airpurifier_coap platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/philips_airpurifier_coap/fan.py", line 32, in async_setup_entry
    fan_entity = model_class(hass, entry, config_entry_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 187, in __init__
    | FanEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_OFF'
2024-11-15 13:07:05.205 ERROR (MainThread) [homeassistant.components.fan] Error while setting up philips_airpurifier_coap platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/philips_airpurifier_coap/fan.py", line 32, in async_setup_entry
    fan_entity = model_class(hass, entry, config_entry_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 187, in __init__
    | FanEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_OFF'

**Comment by kongo09** [comment]
Which version are you using?

**Comment by kongo09** [comment]
And are you using the latest version of Home Assistant?

**Comment by kongo09** [comment]
version v0.23.1 fixes the first bug in your log - maybe that also helps fixing the rest? Can you please try?

**Comment by AlexisBild77** [comment]
Hello, I'm now updated to version 23.1 and using ha 2024.7.2 docker
Still getting this:
AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_OFF'

I'll probably upgrade to 2024.11 and let you know if anything changes

**Comment by kongo09** [comment]
Very strange. `FanEntityFeature` definitely has an attribute `TURN_OFF`

https://github.com/home-assistant/core/blob/75199a901f76b7b8958bd3ef7179a606f0757000/homeassistant/components/fan/__init__.py#L60

**Comment by kongo09** [comment]
I checked 2024.7.2 and indeed, it doesn't have the `TURN_OFF` feature:

https://github.com/home-assistant/core/blob/058b012e6c8af4b8b2eb9010ef3a6042870cf9bf/homeassistant/components/fan/__init__.py#L49

This explains your error. It arrives in 2024.8.0. I should make that a minimum requirement.
