### ISSUE TITLE
aioairctrl not found!

### ISSUE THREAD

**Issue by vz-john** [kongo09/philips-airpurifier-coap#202]
'philips_airpurifier_coap': Unable to import component: No module named 'aioairctrl'

philips_airpurifier_coap: 0.24.0
HomeAssistant: Docker v2024.11.3

**Comment by kongo09** [comment]
Can you please post full logs

**Comment by vz-john** [comment]
2024-11-22 18:40:04.310 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration philips_airpurifier_coap: No module named 'aioairctrl'

**Comment by kongo09** [comment]
Can you please post the full starting log of HA

**Comment by kongo09** [comment]
Have you installed via HACS or manually?

**Comment by vz-john** [comment]
Hi, I have install via HACS, and solve the problem installing manually with "pip install aioairctrl".
But i need to exec every time that I update HA.

**Comment by vz-john** [comment]
Registrador: homeassistant.setup
Fuente: setup.py:334
Ocurrió por primera vez: 21:39:13 (1 ocurrencias)
Última vez registrado: 21:39:13

Setup failed for custom integration 'philips_airpurifier_coap': Unable to import component: No module named 'aioairctrl'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/philips_airpurifier_coap/__init__.py", line 13, in <module>
    from aioairctrl import CoAPClient
ModuleNotFoundError: No module named 'aioairctrl'

**Comment by kongo09** [comment]
This sounds more like a home assistant bug than an integration bug. The module is normally loaded by HA automatically when the integration is loaded. It is given as a dependency in the manifest. I have no idea why this doesn't happen for you and don't know how I could debug it.

I suggest you write an issue at home assistant core. Sorry, that I cannot be of more help.

**Comment by vz-john** [comment]
Workarround
Solved with:
...
    env:
            - name: "PYTHONPATH"
              value: "/usr/local/lib/python3.12:/config/deps"
...
To help others!
https://github.com/home-assistant/core/issues/127966#issuecomment-2471120613
