### ISSUE TITLE
Can't add Philips AC1715/11 devices

### ISSUE THREAD

**Issue by Qualm8429** [kongo09/philips-airpurifier-coap#210]
Hello,

I would like to integrate a Philips AC1715/11. Unfortunately, it doesn't work. When I enter the IP address, "Cannot connect to device" appears.

The AC4236/10 is working flawlessly.

Philips AirPurifier (with CoAP): v0.28.0

Log:
2024-11-25 09:10:08.859 DEBUG (MainThread) [coap] Sending request - Token: d28e, Remote: <UDP6EndpointAddress 192.168.178.120>
2024-11-25 09:10:08.859 DEBUG (MainThread) [coap] Sending message <aiocoap.Message at 0x7f354c7b6300: NON POST (MID 25314, token d28e) remote <UDP6EndpointAddress 192.168.178.120>, 1 option(s), 8 byte(s) payload>
2024-11-25 09:10:08.908 DEBUG (MainThread) [coap] Socket error recevied, details: SockExtendedErr(ee_errno=111, ee_origin=2, ee_type=3, ee_code=3, ee_pad=0, ee_info=0, ee_data=0)
2024-11-25 09:10:08.910 DEBUG (MainThread) [coap] Incoming error [Errno 111] Connection refused (ECONNREFUSED, received through errqueue) from <UDP6EndpointAddress 192.168.178.120 (locally 192.168.178.48%enp1s0)>
2024-11-25 09:10:08.910 WARNING (MainThread) [custom_components.philips_airpurifier_coap.config_flow] Failed to connect: [Errno 111] Connection refused (ECONNREFUSED, received through errqueue)
2024-11-25 09:10:10.243 ERROR (MainThread) [coap] Connection loss was not expected.

**Comment by kongo09** [comment]
Can you connect to it from the command line using `aioairctrl` as described in the README?

**Comment by Qualm8429** [comment]
![image](https://github.com/user-attachments/assets/986dcb07-4bab-484e-9dd0-82ca319434ad)

**Comment by Qualm8429** [comment]
This?

**Comment by kongo09** [comment]
Can you leave out the $ in front of the IP address and try again?

**Comment by Nica-Alex** [comment]
Same here
```
% aioairctrl --host 192.168.1.127 status --json
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 1238, in _read_ready
    data, addr = self._sock.recvfrom(self.max_size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "X/bin/aioairctrl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "X/lib/python3.12/site-packages/aioairctrl/cli.py", line 139, in main
    asyncio.run(async_main())
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "X/lib/python3.12/site-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X/lib/python3.12/site-packages/aioairctrl/coap/client.py", line 41, in create
    await obj._init()
  File "X/lib/python3.12/site-packages/aioairctrl/coap/client.py", line 36, in _init
    await self._sync()
  File "X/lib/python3.12/site-packages/aioairctrl/coap/client.py", line 57, in _sync
    response = await self._client_context.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X/lib/python3.12/site-packages/aiocoap/protocol.py", line 758, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "X/lib/python3.12/site-packages/aiocoap/protocol.py", line 833, in _run
    blockresponse = await blockrequest.response
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiocoap.error.NetworkError: [Errno 61] Connection refused

------

% ping 192.168.1.127
PING 192.168.1.127 (192.168.1.127): 56 data bytes
64 bytes from 192.168.1.127: icmp_seq=0 ttl=255 time=9.325 ms
64 bytes from 192.168.1.127: icmp_seq=1 ttl=255 time=7.340 ms

**Comment by kongo09** [comment]
This looks like the connectivity problem. Some devices are just not reachable and don't communicate locally. Nothing I can do. I tried to reach out to Philips in the past to get some official documentation, but never got a reply. I also tried to find a way to get listed for their cloud service, but only IFTTT was listed for some time. I guess you're out of luck.

**Comment by Lecso11** [comment]
> This looks like the connectivity problem. Some devices are just not reachable and don't communicate locally. Nothing I can do. I tried to reach out to Philips in the past to get some official documentation, but never got a reply. I also tried to find a way to get listed for their cloud service, but only IFTTT was listed for some time. I guess you're out of luck.

Can you tell me what you would need from Philips? I could try with my local support, maybe I get lucky. I have 1715/11 too.

**Comment by kongo09** [comment]
One alternative would be if Philips gives access to their cloud API, which IFTT was using in the past and Alexa still uses. We could then extend the integration to offer that as an alternative.

**Comment by nd3442** [comment]
Having the same issue. It sucks :/

For some reason the COAP port is closed on my AC1715/11
