### ISSUE TITLE
Introduce icons.json based icon translations

### ISSUE THREAD

**Issue by kongo09** [kongo09/philips-airpurifier-coap#211]
The use of the icon attribute for entities seems to be phased out and instead a new approach with icon translations is used:
https://developers.home-assistant.io/blog/2024/01/19/icon-translations/

There is already a pending pull request. #142 

It has also come up in this issue: #198

**Comment by merquel** [comment]
Gave some input regarding the humidifier entity on this in https://github.com/kongo09/philips-airpurifier-coap/issues/198#issuecomment-2505110121

**Comment by kongo09** [comment]
I've done a beta with full icon translations (and more): please give it a spin at v0.30.0-beta.1

**Comment by merquel** [comment]
Tried to install v0.30.0-beta.2 but wasn't able to load the integration.

<details>
2024-12-02 03:06:16.069 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration philips_airpurifier_coap - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 185, in async_setup_component
    await future
  File "/usr/src/homeassistant/homeassistant/setup.py", line 185, in async_setup_component
    await future
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    processed_config = conf_util.async_drop_config_annotations(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config.py", line 908, in async_drop_config_annotations
    if integration.domain in config and integration.domain != HOMEASSISTANT_DOMAIN:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'function' is not iterable
</details>

**Comment by kongo09** [comment]
I must have messed something up. Will check later in the week. Probably the SCHEMA.
