### ISSUE TITLE
aiocoap AttributeError

### ISSUE THREAD

**Issue by kongo09** [kongo09/philips-airpurifier-coap#27]
Sometimes, `aiocoap` reports some errors:

```
2022-05-03 17:36:35 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiocoap/tokenmanager.py", line 57, in shutdown
    await self.token_interface.shutdown()
  File "/usr/local/lib/python3.9/site-packages/aiocoap/transports/tcp.py", line 407, in shutdown
    del self._tokenmanager
AttributeError: _tokenmanager
2022-05-03 17:36:35 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiocoap/tokenmanager.py", line 57, in shutdown
    await self.token_interface.shutdown()
  File "/usr/local/lib/python3.9/site-packages/aiocoap/messagemanager.py", line 67, in shutdown
    for messageerror_monitor, cancellable in self._active_exchanges.values():
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by user897943** [comment]
Getting this after updating to HA 2022.5.0:

```
tions   
      
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
2022-05-04 20:32:20 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 649, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop

```

**Comment by kongo09** [comment]
Do you get this at startup or shutdown or out of the blue?

**Comment by user897943** [comment]
I got this after updating a HACS component and restarting HA

**Comment by user897943** [comment]
After it restarted now I'm getting a lot of these:
```
2022-05-04 20:55:49 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...
2022-05-04 20:56:05 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...
2022-05-04 20:56:12 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...
2022-05-04 20:57:27 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...
2022-05-04 20:58:42 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...
2022-05-04 20:58:49 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...
2022-05-04 20:59:05 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...
2022-05-04 21:00:20 INFO (MainThread) [hole] Response from *hole: 200
2022-05-04 21:00:27 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...
2022-05-04 21:01:00 INFO (MainThread) [homeassistant.components.automation.shades_stop_moving_to_reset_status] Shades - Stop moving to reset status: Restarting
2022-05-04 21:01:00 INFO (MainThread) [homeassistant.components.automation.shades_stop_moving_to_reset_status] Shades - Stop moving to reset status: Running automation actions
2022-05-04 21:01:00 INFO (MainThread) [homeassistant.components.automation.shades_stop_moving_to_reset_status] Shades - Stop moving to reset status: Executing step call service
2022-05-04 21:01:01 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...
2022-05-04 21:01:42 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...
2022-05-04 21:02:02 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...
2022-05-04 21:03:43 INFO (MainThread) [custom_components.philips_airpurifier_coap.timer] Calling timeout callback...

```

**Comment by mhetzi** [comment]
@kongo09 
do you think, using a fixed timeout value is a problem? We have a maximum update time in the library ( i used this field to get value of 180 seconds, 60 seconds * 3 missed updates)

**Comment by user897943** [comment]
Just noticed this on the HA settings:
<img width="467" alt="ha_coap" src="https://user-images.githubusercontent.com/5891221/167173191-f83330af-6da1-4496-9656-2cca268611a9.png">

Look how excessive the startup time is compared to the rest... This is sorta why my HA is so slow when restarting now, and sometimes it hangs and I have to restart the container completely, any way I can help with logs?

**Comment by user897943** [comment]
Just restarted to test and it's even worse (making sure you know this is not an attack/criticism of your work, just an observation about the horrendous startup delay)

<img width="472" alt="ha_coap2" src="https://user-images.githubusercontent.com/5891221/167173640-4518f45d-e249-499a-bdea-fb9fb2994767.png">

**Comment by user897943** [comment]
On the logs:
```
Logger: coap
Source: /usr/local/lib/python3.9/site-packages/aiocoap/protocol.py:726
First occurred: 5:25:28 PM (1 occurrences)
Last logged: 5:25:28 PM

An exception that is not an aiocoap Error was raised from a transport; please report this as a bug in aiocoap: AttributeError("'RecvmsgSelectorDatagramTransport' object has no attribute '_fatal_error'")
```
and
```
ogger: coap
Source: /usr/local/lib/python3.9/site-packages/aiocoap/messagemanager.py:405
First occurred: 5:25:28 PM (1 occurrences)
Last logged: 5:25:28 PM

Forcing message to be sent as NON even though specified because transport is shutting down
```
and
```
Logger: custom_components.philips_airpurifier_coap.philips
Source: custom_components/philips_airpurifier_coap/philips.py:98
Integration: Philips AirPurifier (documentation, issues)
First occurred: 5:25:28 PM (1 occurrences)
Last logged: 5:25:28 PM

config not ready, first refresh failed for host 10.0.0.115
```
and
```
Logger: homeassistant.bootstrap
Source: bootstrap.py:428
First occurred: 5:23:26 PM (3 occurrences)
Last logged: 5:25:26 PM

Waiting on integrations to complete setup: philips_airpurifier_coap
```

**Comment by kongo09** [comment]
> I'm getting a lot of these:

These are not errors but just debug output in loglevel `info`. You can ignore that. Eventually, we can tidy this up.

**Comment by kongo09** [comment]
> do you think, using a fixed timeout value is a problem

I was wondering that, too. Also, 180s is quite long. In my experience the device either comes back rather quickly or it is gone for good. Do you see an alternative? Or just a reduction?

**Comment by kongo09** [comment]
> Look how excessive the startup time is compared to the rest..

Yes, that happens when there is no connection to the device. Also see: https://github.com/kongo09/philips-airpurifier-coap/issues/25

I was wondering if the setup can be put into the background. The `shelly` integration does that for battery powered devices that are not always online. And then uses a callback to complete the setup once data comes in

**Comment by user897943** [comment]
> > Look how excessive the startup time is compared to the rest..
> 
> Yes, that happens when there is no connection to the device. Also see: #25
> 
> I was wondering if the setup can be put into the background. The `shelly` integration does that for battery powered devices that are not always online. And then uses a callback to complete the setup once data comes in

I believe that's what I suggested somewhere, to have a timeout of 15 seconds, maybe 20, and then try on the background. As for the 180seconds I have noticed that my purifiers actually do come back online so I think the 180 seconds sometimes work for reconnecting the coap. Anecdotal though, I haven't objectively tested.

**Comment by mhetzi** [comment]
@kongo09 
https://github.com/kongo09/aioairctrl/pull/1
https://github.com/kongo09/philips-airpurifier-coap/pull/29

These changes would use the max_age value from the device, a far a i understand the device ensures to send at this intervall if no sensor values changed

you can change the missed package multiplier here:
in file custom_components/philips_airpurifier_coap/philips.py on line 34: MISSED_PACKAGE_COUNT = 3

**Comment by kongo09** [comment]
@mhetzi 
I've done a new beta with your changes: `v0.10.1-beta`

**Comment by kongo09** [comment]
Hm, I must have made an error, or the library didn't update properly:
![image](https://user-images.githubusercontent.com/640121/167303048-32481c86-8d5c-45bb-b4ba-a26a2b6a235e.png)

```
2022-05-08 16:55:00 WARNING (MainThread) [custom_components.philips_airpurifier_coap.config_flow] Failed to connect: too many values to unpack (expected 2)
2022-05-08 16:55:00 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/config_flow.py", line 76, in async_step_dhcp
    status, _ = await client.get_status()
ValueError: too many values to unpack (expected 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 192, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 190, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/philips_airpurifier_coap/config_flow.py", line 91, in async_step_dhcp
    raise exceptions.ConfigEntryNotReady from ex
homeassistant.exceptions.ConfigEntryNotReady: too many values to unpack (expected 2)
2022-05-08 16:55:03 WARNING (MainThread) [custom_components.philips_airpurifier_coap] Failed to connect to host 192.168.179.7: 
```

**Comment by mhetzi** [comment]
Most likely the lib.
do you see the max_age log? something like this:

`Mai 08 08:21:26 xeon python3[450813]: 2022-05-08 08:21:26 ERROR (MainThread) [aioairctrl.coap.client] response = <aiocoap.Message at 0x7f87646bfd30: Type.NON 2.05 Content (MID 8913, token fc04) remote <UDP6EndpointAddress 192.168.57.91 (locally 192.168.57.219%bond0_iot)>, 3 option(s), 1480 byte(s) payload>

Mai 08 08:21:26 xeon python3[450813]: 2022-05-08 08:21:26 ERROR (MainThread) [aioairctrl.coap.client] response.opt = <aiocoap.options.Options at 0x7f87507b6740: OBSERVE: 8912, CONTENT_FORMAT: 50, MAX_AGE: 60>

Mai 08 08:21:26 xeon python3[450813]: 2022-05-08 08:21:26 ERROR (MainThread) [aioairctrl.coap.client] response.opt.max_age = 60`

i made these debug messages, error messages so the stand out.

**Comment by mhetzi** [comment]
Beta release works, with modified lib, updating via hacs did not update the lib only the component

**Comment by kongo09** [comment]
I'm struggling with the correct requirements line to update the lib. Sorry, not enough experience. Any idea?

Updating it by hand leads to new errors in the HA log:

```
2022-05-08 22:39:53 ERROR (MainThread) [custom_components.philips_airpurifier_coap.philips] _reconnect error
Traceback (most recent call last):
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 90, in _reconnect
    self.client = await CoAPClient.create(self._host)
  File "/usr/local/lib/python3.9/site-packages/aioairctrl/coap/client.py", line 38, in create
    await obj._init()
  File "/usr/local/lib/python3.9/site-packages/aioairctrl/coap/client.py", line 33, in _init
    await self._sync()
  File "/usr/local/lib/python3.9/site-packages/aioairctrl/coap/client.py", line 54, in _sync
    response = await self._client_context.request(request).response
asyncio.exceptions.CancelledError
```

and 

```
2022-05-08 22:39:56 ERROR (SyncWorker_2) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiocoap/tokenmanager.py", line 57, in shutdown
    await self.token_interface.shutdown()
  File "/usr/local/lib/python3.9/site-packages/aiocoap/messagemanager.py", line 67, in shutdown
    for messageerror_monitor, cancellable in self._active_exchanges.values():
AttributeError: 'NoneType' object has no attribute 'values'
2022-05-08 22:39:56 ERROR (SyncWorker_2) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiocoap/tokenmanager.py", line 57, in shutdown
    await self.token_interface.shutdown()
  File "/usr/local/lib/python3.9/site-packages/aiocoap/transports/tcp.py", line 407, in shutdown
    del self._tokenmanager
AttributeError: _tokenmanager
2022-05-08 22:39:56 ERROR (SyncWorker_2) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiocoap/tokenmanager.py", line 57, in shutdown
    await self.token_interface.shutdown()
  File "/usr/local/lib/python3.9/site-packages/aiocoap/messagemanager.py", line 67, in shutdown
    for messageerror_monitor, cancellable in self._active_exchanges.values():
AttributeError: 'NoneType' object has no attribute 'values'
```

do you see those as well?

**Comment by mhetzi** [comment]
Sadly never played with custom integration, until this reconnect problem really got on my nerves, sorry.

The first comes from the cancelling we do in case of timeout. 
the second one comes from time to time, even without my changes. had them since the integration came out (betaboon not yours).

so no new errors, for me at least....

**Comment by kongo09** [comment]
I'll just merge it into main

But if you could help eliminating these errors, that would be great. I just lack the experience

**Comment by kongo09** [comment]
It's getting a bit messy here with a number of error reports that might or might not be related.

- [ ] aoicoap Attribute error - original bug report in this issue
- [x] Runtime error, no running event loop - see #26 
- [x] unpacking error - fixed by now
- [x] asyncio.exceptions.CancelledError - see #35

**Comment by kongo09** [comment]
please try `v0.11.1` which now comes with the latest `aiocoap 0.4.5` and let me know if the problem still exists

**Comment by kongo09** [comment]
the aiocoap Attribute error seems to have disappeared and as there is no further discussion here, I'll close this issue.
