### ISSUE TITLE
RuntimeError: Event loop is closed on shutdown

### ISSUE THREAD

**Issue by kongo09** [kongo09/philips-airpurifier-coap#36]
```
Exception ignored in: <function RecvmsgSelectorDatagramTransport.__del__ at 0x7f11684bdee0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiocoap/util/asyncio/recvmsg.py", line 95, in __del__
    self.close()
  File "/usr/local/lib/python3.9/site-packages/aiocoap/util/asyncio/recvmsg.py", line 83, in close
    self._loop.call_soon(self._protocol.connection_lost, None)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

happens when HA is shutdown

**Comment by kongo09** [comment]
might be a problem of `aiocoap`

https://stackoverflow.com/questions/69991698/asyncio-run-gives-runtimeerror-loop-is-closed

**Comment by kongo09** [comment]
As nobody else is discussing this and I'm not seeing this anymore, I'll close this issue.
