### ISSUE TITLE
Stopped working after HA core update  2022.8.4

### ISSUE THREAD

**Issue by kine90** [kongo09/philips-airpurifier-coap#47]
Hi Kongo,
My AC1214/10 went offline some days ago and never come back. Looks like the problem happened just after I´ve updated HA core to version  2022.8.4.

```
Logger: homeassistant.components.fan
Source: custom_components/philips_airpurifier_coap/philips.py:151
Integration: Fan (documentation, issues)
First occurred: 1:24:14 PM (1 occurrences)
Last logged: 1:24:14 PM

Error while setting up philips_airpurifier_coap platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/philips_airpurifier_coap/fan.py", line 41, in async_setup_entry
    device = model_class(
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 243, in __init__
    super().__init__(coordinator, model, name)
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 201, in __init__
    super().__init__(coordinator)
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 151, in __init__
    self._serialNumber = coordinator.status["DeviceId"]
TypeError: tuple indices must be integers or slices, not str


Logger: homeassistant.components.switch
Source: custom_components/philips_airpurifier_coap/philips.py:151
Integration: Switch (documentation, issues)
First occurred: 1:24:14 PM (1 occurrences)
Last logged: 1:24:14 PM

Error while setting up philips_airpurifier_coap platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/philips_airpurifier_coap/switch.py", line 67, in async_setup_entry
    switches.append(PhilipsSwitch(coordinator, name, model, switch))
  File "/config/custom_components/philips_airpurifier_coap/switch.py", line 88, in __init__
    super().__init__(coordinator)
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 151, in __init__
    self._serialNumber = coordinator.status["DeviceId"]
TypeError: tuple indices must be integers or slices, not str


Logger: homeassistant.components.light
Source: custom_components/philips_airpurifier_coap/philips.py:151
Integration: Light (documentation, issues)
First occurred: 1:24:14 PM (1 occurrences)
Last logged: 1:24:14 PM

Error while setting up philips_airpurifier_coap platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/philips_airpurifier_coap/light.py", line 72, in async_setup_entry
    lights.append(PhilipsLight(coordinator, name, model, light))
  File "/config/custom_components/philips_airpurifier_coap/light.py", line 93, in __init__
    super().__init__(coordinator)
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 151, in __init__
    self._serialNumber = coordinator.status["DeviceId"]
TypeError: tuple indices must be integers or slices, not str


This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/philips_airpurifier_coap/config_flow.py:94
Integration: Philips AirPurifier (documentation, issues)
First occurred: 1:24:46 PM (1 occurrences)
Last logged: 1:24:46 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 249, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/philips_airpurifier_coap/config_flow.py", line 94, in async_step_dhcp
    self._model = status['type']
TypeError: tuple indices must be integers or slices, not str
```

**Comment by kongo09** [comment]
Thanks for reporting. I'm currently on 2022.8.6 and cannot reproduce the error. Let's see if others also chime in.

**Comment by therealeldaria** [comment]
Not sure if this is for the same reason, I just tried to install this, but the Integration does not show up.
I did the steps of installing it inside HACS and restarting Home Assistant, and it shows inside HACS, but when I go to Home Assistant and try to add a new Integration it does not show as an option when searching for Philips.
I use Home Assistant OS version 2022.8.6

**Comment by kongo09** [comment]
Interesting. I just removed mine and added it back in 2022.8.6 without a problem

**Comment by therealeldaria** [comment]
Very odd, after fixing another error with influxdb, all of a sudden it showed up in Integrations. So at least my error is not related to OPS.

**Comment by Orbi-Code** [comment]
@kine90 @therealeldaria @kongo09
There is a problem with the Wi-Fi connection between the "Clean Home+" app and the device.
If you restore the Wi-Fi connection the problem in Home Assistant is solved too.

**Comment by kongo09** [comment]
What does "restore" mean?

This is the first time that I hear that the CleanHome+ app and its connectivity has anything to do with how HA functions.

@kine90 : does that help you? Can we close this issue here?

**Comment by Orbi-Code** [comment]
@kongo09
> If you restore the Wi-Fi connection the problem in Home Assistant is solved too.

I meant that if you reconnect to your own Wi-Fi network in the CleanHome+ app, the problem is solved.

**Comment by kongo09** [comment]
I guess this is solved. If not, please reopen.

**Comment by kine90** [comment]
Hi @kongo09 , I´ve finally found some time to test this. I am using the beta release specifically made for this model. After connecting the purifier to wifi and adding a new device trough the integration it works, but only for few hours. Now it is already back to unavailable. Rebooting HA or the purifier has any effect. The log shows always the same errors about tuples. 
Now I am  using:
Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

The errors are:

`Logger: homeassistant.bootstrap
Source: bootstrap.py:441
First occurred: 10:39:03 AM (1 occurrences)
Last logged: 10:39:03 AM

Waiting on integrations to complete setup: philips_airpurifier_coap`

`Logger: homeassistant.components.fan
Source: custom_components/philips_airpurifier_coap/philips.py:151
Integration: Fan (documentation, issues)
First occurred: 10:39:07 AM (1 occurrences)
Last logged: 10:39:07 AM

Error while setting up philips_airpurifier_coap platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/philips_airpurifier_coap/fan.py", line 41, in async_setup_entry
    device = model_class(
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 243, in __init__
    super().__init__(coordinator, model, name)
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 201, in __init__
    super().__init__(coordinator)
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 151, in __init__
    self._serialNumber = coordinator.status["DeviceId"]
TypeError: tuple indices must be integers or slices, not str
`
`Logger: homeassistant.components.switch
Source: custom_components/philips_airpurifier_coap/philips.py:151
Integration: Switch (documentation, issues)
First occurred: 10:39:07 AM (1 occurrences)
Last logged: 10:39:07 AM

Error while setting up philips_airpurifier_coap platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/philips_airpurifier_coap/switch.py", line 67, in async_setup_entry
    switches.append(PhilipsSwitch(coordinator, name, model, switch))
  File "/config/custom_components/philips_airpurifier_coap/switch.py", line 88, in __init__
    super().__init__(coordinator)
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 151, in __init__
    self._serialNumber = coordinator.status["DeviceId"]
TypeError: tuple indices must be integers or slices, not str
`

`Logger: homeassistant.components.light
Source: custom_components/philips_airpurifier_coap/philips.py:151
Integration: Light (documentation, issues)
First occurred: 10:39:07 AM (1 occurrences)
Last logged: 10:39:07 AM

Error while setting up philips_airpurifier_coap platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/philips_airpurifier_coap/light.py", line 72, in async_setup_entry
    lights.append(PhilipsLight(coordinator, name, model, light))
  File "/config/custom_components/philips_airpurifier_coap/light.py", line 93, in __init__
    super().__init__(coordinator)
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 151, in __init__
    self._serialNumber = coordinator.status["DeviceId"]
TypeError: tuple indices must be integers or slices, not str
`
`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/philips_airpurifier_coap/config_flow.py:94
Integration: Philips AirPurifier (documentation, issues)
First occurred: 10:39:25 AM (1 occurrences)
Last logged: 10:39:25 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/philips_airpurifier_coap/config_flow.py", line 94, in async_step_dhcp
    self._model = status['type']
TypeError: tuple indices must be integers or slices, not str
`

**Comment by kine90** [comment]
Here the full debug log:
`2022-11-15 11:43:10.199 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.philips] finished first refresh for host 192.168.2.50
2022-11-15 11:43:10.199 DEBUG (MainThread) [custom_components.philips_airpurifier_coap] coordinator did first refresh for host 192.168.2.50
2022-11-15 11:43:10.209 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.fan] async_setup_entry called for platform fan
2022-11-15 11:43:10.210 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.philips] PhilipsEntity __init__ called
2022-11-15 11:43:10.210 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.philips] coordinator.status is: ({'name': 'Marco', 'type': 'AC1214', 'modelid': 'AC1214/10', 'swversion': '2.0.0', 'range': 'Simba', 'Runtime': 94664704, 'rssi': -39, 'otacheck': False, 'wifilog': False, 'free_memory': 54880, 'WifiVersion': 'AWS_Philips_AIR@71.3', 'ProductId': 'dca8c9d2f2ab11e8a1e3061302926720', 'DeviceId': '2b36c7fe68c211ec837242a9fde9d653', 'StatusType': 'status', 'ConnectType': 'Online', 'om': '2', 'pwr': '1', 'cl': False, 'aqil': 50, 'uil': '1', 'dt': 0, 'dtrs': 0, 'mode': 'P', 'pm25': 7, 'iaql': 2, 'aqit': 10, 'aqit_ext': 0, 'ddp': '0', 'err': 0, 'fltt1': 'A3', 'fltt2': 'C7', 'fltsts0': 224, 'fltsts1': 3757, 'fltsts2': 1360}, 60)
2022-11-15 11:43:10.210 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.sensor] async_setup_entry called for platform sensor
2022-11-15 11:43:10.210 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.switch] async_setup_entry called for platform switch
2022-11-15 11:43:10.210 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.philips] PhilipsEntity __init__ called
2022-11-15 11:43:10.210 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.philips] coordinator.status is: ({'name': 'Marco', 'type': 'AC1214', 'modelid': 'AC1214/10', 'swversion': '2.0.0', 'range': 'Simba', 'Runtime': 94664704, 'rssi': -39, 'otacheck': False, 'wifilog': False, 'free_memory': 54880, 'WifiVersion': 'AWS_Philips_AIR@71.3', 'ProductId': 'dca8c9d2f2ab11e8a1e3061302926720', 'DeviceId': '2b36c7fe68c211ec837242a9fde9d653', 'StatusType': 'status', 'ConnectType': 'Online', 'om': '2', 'pwr': '1', 'cl': False, 'aqil': 50, 'uil': '1', 'dt': 0, 'dtrs': 0, 'mode': 'P', 'pm25': 7, 'iaql': 2, 'aqit': 10, 'aqit_ext': 0, 'ddp': '0', 'err': 0, 'fltt1': 'A3', 'fltt2': 'C7', 'fltsts0': 224, 'fltsts1': 3757, 'fltsts2': 1360}, 60)
2022-11-15 11:43:10.211 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.light] async_setup_entry called for platform switch
2022-11-15 11:43:10.211 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.philips] PhilipsEntity __init__ called
2022-11-15 11:43:10.211 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.philips] coordinator.status is: ({'name': 'Marco', 'type': 'AC1214', 'modelid': 'AC1214/10', 'swversion': '2.0.0', 'range': 'Simba', 'Runtime': 94664704, 'rssi': -39, 'otacheck': False, 'wifilog': False, 'free_memory': 54880, 'WifiVersion': 'AWS_Philips_AIR@71.3', 'ProductId': 'dca8c9d2f2ab11e8a1e3061302926720', 'DeviceId': '2b36c7fe68c211ec837242a9fde9d653', 'StatusType': 'status', 'ConnectType': 'Online', 'om': '2', 'pwr': '1', 'cl': False, 'aqil': 50, 'uil': '1', 'dt': 0, 'dtrs': 0, 'mode': 'P', 'pm25': 7, 'iaql': 2, 'aqit': 10, 'aqit_ext': 0, 'ddp': '0', 'err': 0, 'fltt1': 'A3', 'fltt2': 'C7', 'fltsts0': 224, 'fltsts1': 3757, 'fltsts2': 1360}, 60)
2022-11-15 11:43:10.211 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.select] async_setup_entry called for platform select
2022-11-15 11:43:10.215 ERROR (MainThread) [homeassistant.components.fan] Error while setting up philips_airpurifier_coap platform for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/philips_airpurifier_coap/fan.py", line 41, in async_setup_entry
device = model_class(
File "/config/custom_components/philips_airpurifier_coap/philips.py", line 243, in __init__
super().__init__(coordinator, model, name)
File "/config/custom_components/philips_airpurifier_coap/philips.py", line 201, in __init__
super().__init__(coordinator)
File "/config/custom_components/philips_airpurifier_coap/philips.py", line 151, in __init__
self._serialNumber = coordinator.status["DeviceId"]
TypeError: tuple indices must be integers or slices, not str
2022-11-15 11:43:10.221 ERROR (MainThread) [homeassistant.components.switch] Error while setting up philips_airpurifier_coap platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/philips_airpurifier_coap/switch.py", line 67, in async_setup_entry
switches.append(PhilipsSwitch(coordinator, name, model, switch))
File "/config/custom_components/philips_airpurifier_coap/switch.py", line 88, in __init__
super().__init__(coordinator)
File "/config/custom_components/philips_airpurifier_coap/philips.py", line 151, in __init__
self._serialNumber = coordinator.status["DeviceId"]
TypeError: tuple indices must be integers or slices, not str
2022-11-15 11:43:10.224 ERROR (MainThread) [homeassistant.components.light] Error while setting up philips_airpurifier_coap platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/philips_airpurifier_coap/light.py", line 72, in async_setup_entry
lights.append(PhilipsLight(coordinator, name, model, light))
File "/config/custom_components/philips_airpurifier_coap/light.py", line 93, in __init__
super().__init__(coordinator)
File "/config/custom_components/philips_airpurifier_coap/philips.py", line 151, in __init__
self._serialNumber = coordinator.status["DeviceId"]
TypeError: tuple indices must be integers or slices, not str`

**Comment by kine90** [comment]
@kongo09, the main problem was definitely due to client.get_status() returning a tuple 
`coordinator.status is: ({'name': 'Marco', 'type': 'AC1214', 'modelid': 'AC1214/10', 'swversion': '2.0.0', 'range': 'Simba', 'Runtime': 94664704, 'rssi': -39, 'otacheck': False, 'wifilog': False, 'free_memory': 54880, 'WifiVersion': 'AWS_Philips_AIR@71.3', 'ProductId': 'dca8c9d2f2ab11e8a1e3061302926720', 'DeviceId': '2b36c7fe68c211ec837242a9fde9d653', 'StatusType': 'status', 'ConnectType': 'Online', 'om': '2', 'pwr': '1', 'cl': False, 'aqil': 50, 'uil': '1', 'dt': 0, 'dtrs': 0, 'mode': 'P', 'pm25': 7, 'iaql': 2, 'aqit': 10, 'aqit_ext': 0, 'ddp': '0', 'err': 0, 'fltt1': 'A3', 'fltt2': 'C7', 'fltsts0': 224, 'fltsts1': 3757, 'fltsts2': 1360}, 60)`
while the resto of the code expects a dictionary.

In the newer releases of the integration this has been fixed unpacking the tuple before accessing the dict:
`self.status, timeout = await self.client.get_status()
self._timeout = timeout`

Updating to the last release fixes the errors, but I am back with the problem that I can´t get the modes working properly.

Now, I have almost everything working by doing the following mash-up of releases:
1. Installed the last release
2. From philips.py release v0.10.1-beta1214.1 I´ve copied the class `PhilipsAC1214(PhilipsGenericCoAPFan)` and pasted it to replace the same class in the newer philips.py

I´ll keep it under test to see if the fix lasts in the next days.
Thanks!

**Comment by kine90** [comment]
The issue seems to be solved updating to the last version for AC1214/10. After one week of successful testing I made a pull request to merge it to the main branch. #52
