### ISSUE TITLE
AC0650 Support ?

### ISSUE THREAD

**Issue by Seidel76** [kongo09/philips-airpurifier-coap#96]
Is it possible to support AC0650 Air Purifier ?

This one: https://www.amazon.fr/Philips-Purificateur-Ultra-silencieux-AC0650-10/dp/B0BX49FQF8

Thanks !

**Comment by damda58** [comment]
If I can be useful for porting do not hesitate, if you need more information on this model I have an AC0650 available

**Comment by kongo09** [comment]
In any case I would need the data response as described in the readme here

**Comment by Seidel76** [comment]
Yes but I've this error:

`(env) pi@raspberrypi:~ $ aioairctrl --host 192.168.0.92 status --json
ConnectionRefusedError: [Errno 111] received through errqueue

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/env/bin/aioairctrl", line 8, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.9/site-packages/aioairctrl/cli.py", line 139, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/env/lib/python3.9/site-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
  File "/home/pi/env/lib/python3.9/site-packages/aioairctrl/coap/client.py", line 38, in create
    await obj._init()
  File "/home/pi/env/lib/python3.9/site-packages/aioairctrl/coap/client.py", line 33, in _init
    await self._sync()
  File "/home/pi/env/lib/python3.9/site-packages/aioairctrl/coap/client.py", line 54, in _sync
    response = await self._client_context.request(request).response
  File "/home/pi/env/lib/python3.9/site-packages/aiocoap/protocol.py", line 606, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/home/pi/env/lib/python3.9/site-packages/aiocoap/protocol.py", line 665, in _run
    blockresponse = await blockrequest.response
aiocoap.error.NetworkError: [Errno 111] received through errqueue`

This is the correct IP and I activated turbo and medium mode before executing the command, my internet box says that the device is connected and so does the Philips application.

**Comment by kongo09** [comment]
It might be that the device doesn't speak encrypted coap.

@damda58 : do you have the same problem?

**Comment by damda58** [comment]
Yep, When I try to integrate it with home assistant via its IP address I get an error saying the device cannot be found.

**Comment by kongo09** [comment]
That is not surprising as the device is not supported yet. What about trying to get its data via the command line?

**Comment by damda58** [comment]
How to do this?

**Comment by kongo09** [comment]
Check the readme

**Comment by damda58** [comment]
Yes 

`(env) root@test-python:~# aioairctrl -H 192.168.1.212 status
ConnectionRefusedError: [Errno 111] received through errqueue

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/env/bin/aioairctrl", line 10, in <module>
    sys.exit(main())
  File "/root/env/lib/python3.7/site-packages/aioairctrl/cli.py", line 139, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/root/env/lib/python3.7/site-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
  File "/root/env/lib/python3.7/site-packages/aioairctrl/coap/client.py", line 38, in create
    await obj._init()
  File "/root/env/lib/python3.7/site-packages/aioairctrl/coap/client.py", line 33, in _init
    await self._sync()
  File "/root/env/lib/python3.7/site-packages/aioairctrl/coap/client.py", line 54, in _sync
    response = await self._client_context.request(request).response
  File "/root/env/lib/python3.7/site-packages/aiocoap/protocol.py", line 606, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/root/env/lib/python3.7/site-packages/aiocoap/protocol.py", line 665, in _run
    blockresponse = await blockrequest.response`

**Comment by kongo09** [comment]
I guess then your device doesn't work, sorry.

**Comment by fodorg01** [comment]
Hi,
with the same device (AC0650) I have also the very same problem as @Seidel76 had, when I try to execute the instructions from readme:

ConnectionRefusedError: [Errno 111] received through errqueue

The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
    File "/usr/local/bin/aioairctrl", line 8, in <module>
        sys.exit(main())
    File "/usr/local/lib/python3.8/dist-packages/aioairctrl/cli.py", line 139, in main
        asyncio.run(async_main())
    File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
        return loop.run_until_complete(main)
    File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
    File "/usr/local/lib/python3.8/dist-packages/aioairctrl/cli.py", line 97, in async_main
        client = await CoAPClient.create(host=args.host, port=args.port)
    File "/usr/local/lib/python3.8/dist-packages/aioairctrl/coap/client.py", line 38, in create
        await obj._init()
    File "/usr/local/lib/python3.8/dist-packages/aioairctrl/coap/client.py", line 33, in _init
        await self._sync()
    File "/usr/local/lib/python3.8/dist-packages/aioairctrl/coap/client.py", line 54, in _sync
        response = await self._client_context.request(request).response
    File "/usr/local/lib/python3.8/dist-packages/aiocoap/protocol.py", line 606, in _run_outer
        await cls._run(app_request, response, weak_observation, protocol, log)
    File "/usr/local/lib/python3.8/dist-packages/aiocoap/protocol.py", line 665, in _run
        blockresponse = await blockrequest.response
    aiocoap.error.NetworkError: [Errno 111] received through errqueue

So it seems like the device doesn't support that kind of communication which is expected by the aioairctrl tool.
